name: CI & CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Root Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies & Run tests
        run: |
          npm install
          npm test

  build_and_push:
    needs: test
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push WS Server Image
        run: |
          docker build -f ws-server.Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/ws-server:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ws-server:latest
      - name: Build & Push Dashboard Image
        run: |
          docker build -f dashboard/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/dashboard:latest dashboard
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dashboard:latest
